### ISSUE TITLE
2018年5月のpotatotips （株式会社CAMPFIRE様）

### ISSUE THREAD

**Issue by tokorom** [potatotips/potatotips#46]

**Comment by nakajijapan** [comment]
@tokorom 弊社でやらせてください！

株式会社CAMPFIRE
https://campfire.co.jp/

**Comment by tokorom** [comment]
@nakajijapan ご連絡ありがとうございます！是非お願いいたします。

**Comment by nakajijapan** [comment]
5/23(水)    に確定しました！
随時諸々進めてまいります。

**Comment by nakajijapan** [comment]
# TODO

- [ ] Hosted Byの社名記載に変更の必要がありましたら修正をお願いします
- [ ] Organizer（イベント管理者）を必要に応じて追加をお願いします
- [ ] Event Imageの登録（御社が主催であることが視覚的に分かる写真 or 会場の雰囲気が分かるものが良いかと思います）
- [ ] 募集枠の人数を会場や御社ご状況に合わせてご変更ください（現在のものは所が適当に入力したものです）
- [ ] DescriptionのTODOマークが付いている箇所、および変更の必要な箇所がありましたら編集をお願いします
- [ ] 会場の設定をお願いします
    - [ ] connpass上に表示される会場の地図と実際の位置が一致しているかをご確認ください（connpassの地図は住所からの逆引きで位置情報が設定されるのですが、過去にその位置情報がずれているという事故が発生したためです）
- [ ] LTの前後に御社のご紹介や宣伝など、必要でしたらご自由に差し込みをお願いします（イベントページに記載の必要はありません）
- [ ] 必要でしたら応募者の中から特定のかたの当選のご指名（connpass上で可能です）いただいて構いません
- [ ] 参考情報をご一読ください：potatotips開催 Tips https://github.com/potatotips/potatotips/wiki/potatotips開催-Tips
- [ ] 上記が終わりましたらそのまま公開いただいてかまいません

**Comment by tokorom** [comment]
@nakajijapan Check List作成いただきありがとうございました！

先ほど、connpassにイベントページのドラフトを作成し、nakajijapanさんを管理者として追加させていただきました。

https://connpass.com/event/85155/edit/

お手数ですが上記Check Listを良きタイミングでおすすめください。

**Comment by tokorom** [comment]
すみません。今気づいたのですが、既に

https://potatotips.connpass.com/event/85025/preview/

で作成いただいておりましたね。こちらをそのままご利用いただく形でもちろん大丈夫です。

**Comment by tokorom** [comment]
@nakajijapan 

先ほど、LT発表順をランダムに決定し、こちらに記載をさせていただきました。

https://github.com/potatotips/potatotips/wiki/potatotips-51

御社からのご発表者やゲストなどございましたらこちらに追記をお願いします。

**Comment by nakajijapan** [comment]
すいませんお手数おかけしました。。。
